<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Dashboard extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pesertum_model');
				$this->load->library("Pdf");
        
    }


    function index()
    {
				$this->load->model('Logdownload_model');
				$data['jumlahrecord'] = $this->Logdownload_model->get_all_logdownload();
				
				$this->load->view('dashboard',$data);
    }

    function searchPeserta()
	{
		$q = $this->input->get('q');
		echo json_encode($this->Pesertum_model->getPeserta($q));
	}
	
	function lihatdata ()
	{
			$data['pesertum'] = $this->Pesertum_model->get_pesertum($this->input->post('nopeserta'));
			$this->load->view('lihatpeserta',$data);
	}
	
	function cetak()
    {
			$this->load->model('Logdownload_model');
			$params = array(
				'nopeserta' => $this->input->post('nopeserta'),
				'datetime' => date("Y-m-d H:i:s"),
            );
			$this->Logdownload_model->add_logdownload($params);
			$data['pesertum'] = $this->Pesertum_model->get_pesertum($this->input->post('nopeserta'));
			$this->load->view('cetak',$data);
    }
}