<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pesertum extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Pesertum_model');
    } 

    /*
     * Listing of peserta
     */
    function index()
    {
        $data['peserta'] = $this->Pesertum_model->get_all_peserta();
        
        $data['_view'] = 'pesertum/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new pesertum
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'namapeserta' => $this->input->post('namapeserta'),
				'prodi' => $this->input->post('prodi'),
				'jenjang' => $this->input->post('jenjang'),
				'fakultas' => $this->input->post('fakultas'),
				'suku' => $this->input->post('suku'),
				'asalslta' => $this->input->post('asalslta'),
            );
            
            $pesertum_id = $this->Pesertum_model->add_pesertum($params);
            redirect('pesertum/index');
        }
        else
        {            
            $data['_view'] = 'pesertum/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a pesertum
     */
    function edit($nopeserta)
    {   
        // check if the pesertum exists before trying to edit it
        $data['pesertum'] = $this->Pesertum_model->get_pesertum($nopeserta);
        
        if(isset($data['pesertum']['nopeserta']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'namapeserta' => $this->input->post('namapeserta'),
					'prodi' => $this->input->post('prodi'),
					'jenjang' => $this->input->post('jenjang'),
					'fakultas' => $this->input->post('fakultas'),
					'suku' => $this->input->post('suku'),
					'asalslta' => $this->input->post('asalslta'),
                );

                $this->Pesertum_model->update_pesertum($nopeserta,$params);            
                redirect('pesertum/index');
            }
            else
            {
                $data['_view'] = 'pesertum/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The pesertum you are trying to edit does not exist.');
    } 

    /*
     * Deleting pesertum
     */
    function remove($nopeserta)
    {
        $pesertum = $this->Pesertum_model->get_pesertum($nopeserta);

        // check if the pesertum exists before trying to delete it
        if(isset($pesertum['nopeserta']))
        {
            $this->Pesertum_model->delete_pesertum($nopeserta);
            redirect('pesertum/index');
        }
        else
            show_error('The pesertum you are trying to delete does not exist.');
    }
    
}
