<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Logdownload_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get logdownload by idlog
     */
    function get_logdownload($idlog)
    {
        return $this->db->get_where('logdownload',array('idlog'=>$idlog))->row_array();
    }
        
    /*
     * Get all logdownload
     */
    function get_all_logdownload()
    {
				$this->db->distinct();
				$this->db->select('nopeserta');
        return $this->db->get('logdownload')->num_rows();
    }
        
    /*
     * function to add new logdownload
     */
    function add_logdownload($params)
    {
        $this->db->insert('logdownload',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update logdownload
     */
    function update_logdownload($idlog,$params)
    {
        $this->db->where('idlog',$idlog);
        return $this->db->update('logdownload',$params);
    }
    
    /*
     * function to delete logdownload
     */
    function delete_logdownload($idlog)
    {
        return $this->db->delete('logdownload',array('idlog'=>$idlog));
    }
}
