<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pengaturan_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function getSetting($param)
    {
        $this->db->select('nilai');
        $this->db->where('parameter', $param);
        $query = $this->db->get('pengaturan');
        return $query->row()->nilai;
    }
}