<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Pesertum_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get pesertum by nopeserta
     */
    function get_pesertum($nopendaftar)
    {
        return $this->db->get_where('v_penerimaanx',array('nopendaftar'=>$nopendaftar))->row_array();
    }
        
    /*
     * Get all peserta
     */
    function get_all_peserta()
    {
        $this->db->order_by('nopendaftar', 'desc');
        return $this->db->get('v_penerimaanx')->result_array();
    }
        
    /*
     * function to add new pesertum
     */
    function add_pesertum($params)
    {
        $this->db->insert('peserta',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update pesertum
     */
    function update_pesertum($nopeserta,$params)
    {
        $this->db->where('nopeserta',$nopeserta);
        return $this->db->update('peserta',$params);
    }
    
    /*
     * function to delete pesertum
     */
    function delete_pesertum($nopeserta)
    {
        return $this->db->delete('peserta',array('nopeserta'=>$nopeserta));
    }
}
